permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Shuzhou Zhang
  email: zhangshuzhou.hi@163.com
  link: http://zhangshuzhou.cn
#  weibo: http://weibo.com/orangeissweet
  github: http://github.com/shuzhou
#  music: http://site.douban.com/linanya
#  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 张书洲的博客
description: My personal blog
baseurl: /
# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: zhangshuzhou.cn

# disqus 设置
disqus:
  shortname: zhangshuzhou

# 主题设置，自动激活某个标签
active: linux

# 首页除了最新文章外显示分类
cates: 
  - 机器学习
  - 开发语言

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
